Release ROX-Filer 2.12 GTK3 r56

diff --git a/Choices/MIME-types/text_html b/Choices/MIME-types/text_html
--- a/Choices/MIME-types/text_html
+++ b/Choices/MIME-types/text_html
@@ -1,2 +1,13 @@
 #!/bin/sh
-exec defaulthtmlviewer "$@"
+
+for app in firefox mozilla-firefox firebird mozilla-firebird galeon mozilla netscape skipstone dillo konqueror amaya; do
+  if [ -x "`which $app`" ]; then exec "$app" "$@"; fi
+done
+
+for app in w3m lynx links vim vi; do
+  if [ -x "`which $app`" ]; then exec xterm -e "$app" "$@"; fi
+done
+
+echo "Can't find any web browser installed... last try..." >&2
+
+exec netscape "$@"
